export const employeeList = [
    {
        firstName: 'Paul',
        lastName: 'Arcelin',
        dateOfBirth: '1987-09-09',
        startDate: '2020-01-01',
        street: 'Victor Hugo',
        city: 'Charenton',
        addressState: 'Val de Marne',
        zipCode: '94220',
        department: 'IT',
    },
    {
        firstName: 'Mario',
        lastName: 'Bros',
        dateOfBirth: '1958-08-08',
        startDate: '2022-02-02',
        street: 'Peach',
        city: 'Champi',
        addressState: 'Tuyau',
        zipCode: '123',
        department: 'Plombier',
    },
    {
        firstName: 'Donkey',
        lastName: 'Kong',
        dateOfBirth: '1991-09-09',
        startDate: '2023-01-01',
        street: 'Banane',
        city: 'DK',
        addressState: 'Seine st Denis',
        zipCode: '321',
        department: 'Marketing',
    },
    {
        firstName: 'Luke',
        lastName: 'Skywalker',
        dateOfBirth: '1978-10-09',
        startDate: '2018-01-01',
        street: 'Rebel',
        city: 'Tatooine',
        addressState: 'Désert',
        zipCode: '1254',
        department: 'Jedi',
    },
]